services:
  front:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - $HOME/github.com/loicbourgois/vellipsis/front:/usr/share/nginx/html:ro
  web_gpu:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - $HOME/github.com/loicbourgois/vellipsis/web-gpu:/usr/share/nginx/html:ro
